### ISSUE TITLE
Auth Error

### ISSUE THREAD

**Issue by jgantenberg** [armooo/cloudprint#100]
I get the following error and can't find an information:
  File "/usr/share/cloudprint/cloudprint/rest.py", line 105, in rest_call
    raise REST.RESTException('REST Error', resp.status, data)
cloudprint.rest.RESTException: REST Error:403
Message: <HTML>
<HEAD>
<TITLE>User credentials required</TITLE>
</HEAD>
<BODY BGCOLOR="#FFFFFF" TEXT="#000000">
<H1>User credentials required</H1>
<H2>Error 403</H2>
</BODY>
</HTML>

when I try to connect to google cloudprint service. I have 2-factor-auth enabled and created an application password. I use the actual version 0.11-9 on a debian installation. 
Any ideas?

**Comment by armooo** [comment]
Google removed support for the style of auth that was being used. This was fixed in this repo on master by using the new OAuth2 printer register flow. @davesteele looks to have added OAuth2 support in https://github.com/davesteele/cloudprint-service/blob/master/debian/patches/0025-Remove-GNOME-requirement-for-OAuth2.patch which requires you to run cpoauth.py first to generate an OAuth2 token. (I think this is how it works I have not used it)

You can try to use master here, or pip install cloudprint. Otherwise open a bug on https://github.com/davesteele/cloudprint-service .
