### ISSUE TITLE
Cloudprint not updating to latest version

### ISSUE THREAD

**Issue by mhoam** [armooo/cloudprint#116]
Hi,
Around 3 months ago I  successfully installed cloudprint and cloudprint service on a Raspberry 2 running Jessie (Debian 8) by setting up the PPA in my sources list as detailed [here](http://davesteele.github.io/cloudprint-service/ppa.html)

When apt-get update and apt-get upgrade are used, cloudprint is "kept back" and not updated. As a result, the cloudprint package version is out of date (v0.11-9) The cloudprint-service package is up to date (V0.14-3). Systemctl shows that the service is started and running, and that the xmpp connection to google was established.

Apt-get dist-upgrade does not upgrade the cloudprint package either.

When I re-try "apt-get install cloudprint", the following messages appear;
*The following packages have unmet dependencies:
cloudprint : Depends: python-daemon (>= 2.0) but 1.5.5-1 is to be installed
Depends: python-configargparse but it is not installable
E: Unable to correct problems, you have held broken packages.*

it looks like the package "python-configargparse" could be stopping the update, any idea why this is not installable?
thanks

**Comment by davesteele** [comment]
The code pulling in the configargparse module and the Debian packaging is not in this repository.

davesteele/cloudprint-service#40

You *could* install this version of cloudprint using 'pip install cloudprint'. If that installs on top of the Debian-installed script (/usr/bin/cloudprint), you may be good to go.

**Comment by mhoam** [comment]
Apologies for the newbie questions but are you saying that code is not in
the cloudprint  repository YET, or will it never get there?
Also I am not clear from where the "pip" command will pull the latest
version of cloudprint and its dependencies. Will it pull it down from the
Raspbian Jessie repositories identified in the sources.list?
Thanks for your help

**Comment by davesteele** [comment]
I can't say whether or not the code will migrate here - the config file will be submitted as a pull request at some point. You should not expect the process to be quick.

'pip' is an interface to the Python code repository "[PyPi](https://pypi.python.org/pypi)". It serves a similar purpose to 'apt-get', but only for python modules/software. The two services do not interact. It is an option here because cloudprint 0.14 requires a new, incompatible version of python-daemon (which is not in Jessie). Pip would cause the right one to be installed, on top of whatever apt-get had done. In that case, apt-get would not be aware of the upgrade.

**Comment by armooo** [comment]
Looks like a downstream packaging bug. I am guessing the PPA is built for stretch/sid and python-configargparse can not be found on jessie.
