### ISSUE TITLE
Which one do I need? 'cloudprint' or 'cups-connector' or 'cupscloudprint' ?

### ISSUE THREAD

**Issue by davigre** [armooo/cloudprint#124]
I have a old and only usb Samsung ML-1740 (SDL format - no 'ps', no pdf's) where I want to print from my Android Phone.

I want to use 'Google Cloud Print', but found 3 tools:

[cloudprint](https://github.com/armooo/cloudprint)
[cups-connector](https://github.com/google/cups-connector)
[cupscloudprint](https://github.com/simoncadman/CUPS-Cloud-Print)

Which tool do I need? 

My printer is already connected and working in a CUPS 1.5.3 server, receiving and printing raw, pdf and ps format.

Thank You.

**Comment by davesteele** [comment]
cupscloudprint solves a different problem - printing to Cloudprint using CUPS.

cups-connector is provided by Google. The development community is more active than for the alternatives.

cloudprint is [packaged](http://davesteele.github.io/cloudprint-service/), making installation and service configuration easier. Having said that, note that there are two current packaged versions, one for python-daemon >= 2.0 plus systemd, the other for python-daemon <2.0 plus sysv init scripts. Since you have done a 'pip install daemon', you may need to downgrade that before installing the sysv version.

The level of printer support shouldn't matter in any case, as long as you can e.g. print a PDF.

**Comment by davigre** [comment]
Ok, Thank you.

I investigate and found that cups-connector need's 'Go' language I will stick to 'cloudprint'.
