### ISSUE TITLE
Need Printer to be automatically online when machine reboots

### ISSUE THREAD

**Issue by scoronado12** [armooo/cloudprint#136]
Running this on a Raspberry Pi 2, the entire concept of getting the printer connecting to Google Works perfectly.

The problem is I have to re-register the printer everytime it reboots. Is there something I'm missing from the documentation?

My setup is Raspbian Jessie Lite (I guess you could consider that headless) I don't have X11 installed on it and I interact with its shell via ssh on my local network

Thanks.

**Comment by davesteele** [comment]
sudo apt-get install cloudprint-service

**Comment by stefanocorona12** [comment]
@davesteele I did enable cloudprintd.service

The issue I am now having that may be related is the following
`* cloudprintd.service - Google Cloud Print proxy service
   Loaded: loaded (/lib/systemd/system/cloudprintd.service; enabled)
   Active: activating (auto-restart) (Result: exit-code) since Thu 2017-07-20 00:21:29 EDT; 4min 33s ago
  Process: 421 ExecStart=/usr/sbin/cloudprintd -a /var/lib/cloudprintd/authfile.json (code=exited, status=1/FAILURE)
 Main PID: 421 (code=exited, status=1/FAILURE)
   CGroup: /system.slice/cloudprintd.service

Jul 20 00:21:29 rasp-pi-googlecloud-print systemd[1]: cloudprintd.service: main process exited, code=exited, status=1/FAILURE
Jul 20 00:21:29 rasp-pi-googlecloud-print systemd[1]: Unit cloudprintd.service entered failed state.
`

**Comment by davesteele** [comment]
What output do you get if you run the ExecStart command, as root?

**Comment by stefanocorona12** [comment]
To be honest, that is a bit beyond me. However, I ran the "systemctl restart" command on cloudprintd.service and it started back up.

`* cloudprintd.service - Google Cloud Print proxy service
   Loaded: loaded (/lib/systemd/system/cloudprintd.service; enabled)
   Active: activating (auto-restart) (Result: exit-code) since Thu 2017-07-20 00:21:29 EDT; 4min 33s ago
  Process: 421 ExecStart=/usr/sbin/cloudprintd -a /var/lib/cloudprintd/authfile.json (code=exited, status=1/FAILURE)
 Main PID: 421 (code=exited, status=1/FAILURE)
   CGroup: /system.slice/cloudprintd.service

Jul 20 00:21:29 rasp-pi-googlecloud-print systemd[1]: cloudprintd.service: main process exited, code=exited, status=1/FAILURE
Jul 20 00:21:29 rasp-pi-googlecloud-print systemd[1]: Unit cloudprintd.service entered failed state.
`
